apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: {{ .Values.image.consumer }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-kafka"
            - "kafka:9092"
            - "-clickhouse"
            - "clickhouse:9000"
            - "-topic"
            - {{ .Values.consumer.topic | quote }}
            - "-metrics-port"
            - {{ .Values.consumer.metricsPort | quote }}
          ports:
            - containerPort: {{ .Values.consumer.metricsPort }}
          resources: {{ toYaml .Values.consumer.resources | nindent 12 }}
